name: vup
description: Vup Cloud Storage

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.10.1+1001

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  unicons: ^2.0.1
  hive: ^2.0.4
  flutter_spinkit: ^5.0.0
  clipboard: ^0.1.3
  ffmpeg_kit_flutter_full: ^4.5.0
  skynet:
    # path: ../skynet
    git:
      url: https://github.com/redsolver/skynet.git
      ref: experimental
  # TODO Use biometric_storage or https://pub.dev/packages/flutter_secure_storage
  simple_observable: ^2.0.0
  flutter_svg: ^1.0.1
  path_provider: ^2.0.2
  beamer: ^0.14.0
  path: ^1.8.0
  crypto: ^3.0.1
  convert: ^3.0.0
  mime: ^1.0.0
  multi_split_view: ^1.2.1
  filesize:
    git: https://github.com/redsolver/filesize.git
  timeago: ^3.1.0
  xdg_directories: ^0.2.0
  build_context: ^3.0.0
  file_selector: ^0.8.2+1
  file_selector_linux: ^0.0.2+1
  file_selector_macos: ^0.8.2
  file_selector_windows: ^0.8.2
  file_picker: ^4.1.3
  # path: /home/redsolver/tmp/flutter_file_picker
  permission_handler: ^9.2.0
  hive_flutter: ^1.0.0
  # simple_json_mapper: ^2.1.0
  # workmanager: ^0.4.1
  json_annotation: ^4.0.1
  # android_intent_plus: ^1.0.2
  open_file:
    git:
      url: https://github.com/miDeb/open_file.git
      ref: no_system
  open_settings: ^2.0.1
  flutter_advanced_segment: ^3.0.0
  # libsodium: ^0.2.0
  # flutter_sodium: ^0.2.0
  selectable_autolink_text: ^2.3.0
  url_launcher: ^6.0.9
  html: ^0.15.0
  filesystem_dac:
    # path: ../fs-dac/dac
    git:
      url: https://github.com/redsolver/skyfs
      path: dac
  sodium_libs: ^1.1.1
  sodium: ^1.1.2
  state_notifier: ^0.7.1
  flutter_state_notifier: ^0.7.1
  universal_platform: ^1.0.0+1
  desktop_drop: ^0.1.2
  uuid: ^3.0.5
  flutter_blurhash: ^0.6.0
  pool: ^1.5.0
  adaptive_dialog: ^1.1.0
  intl: ^0.17.0
  shimmer: ^2.0.0
  just_audio: ^0.9.13
  # just_audio_libwinmedia: ^0.0.4
  audio_video_progress_bar: ^0.10.0
  animate_icons: ^2.0.0
  qr_flutter: ^4.0.0
  flutter_local_notifications: ^9.0.0
  flutter_highlight: ^0.7.0
  # new_keyboard_shortcuts: ^0.1.4
  watcher: ^1.0.1
  alfred:
    git:
      url: https://github.com/redsolver/alfred.git
      ref: range-requests
  connectivity_plus: ^2.0.2
  share_plus: ^4.0.3
  package_info_plus: ^1.4.2
  string_validator: ^0.3.0
  # printing: ^5.6.3
  retry: ^3.1.0
  uni_links: ^0.5.1
  device_info_plus: ^3.1.1
  network_info_plus: ^2.1.2
  tray_manager: ^0.1.2
  bitsdojo_window: ^0.1.1+1
  flutter_background: ^1.1.0
  feedback: ^2.2.1
  flutter_colorpicker: ^1.0.3
  stash: ^4.0.1
  stash_hive: ^4.0.1
  tuple: ^2.0.0
  subtitle: ^0.1.0-beta.3
  xml: ^5.3.1
  mno_streamer: ^0.1.1
  archive2:
    git: https://github.com/redsolver/archive.git
  launch_at_startup: ^0.1.5
  hive_crdt: ^2.0.2
  random_string: ^2.3.1
  webdav_client:
    git: https://github.com/redsolver/webdav_client.git
  draggable_scrollbar: ^0.1.0
  lzma: ^1.0.1
  xml2json: ^5.3.2
  dart_chromecast: ^0.3.3
  contextmenu: ^3.0.0

  # flutter_acrylic: ^0.1.0
  # explo_capture: ^0.1.0+2
  # receive_sharing_intent: ^1.4.5

dev_dependencies:
  #flutter_test:
  #  sdk: flutter
  # simple_json: ^2.1.1
  build_runner: ^1.10.0
  hive_generator: ^1.1.0
  json_serializable: ^4.1.3
  flutter_launcher_icons: "^0.9.2"
  dart_code_metrics: ^4.1.0
  msix: ^2.8.5

dependency_overrides:
  #skynet:
  #  path: ../skynet
  path: 1.8.1
  archive: 3.1.5

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  image_path_ios: "assets/icon/ios.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/adaptive_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/vscode-material-icon-theme/
    - assets/images/
    - assets/icon/tray_icon.png
    - assets/icon/tray_icon.ico
    - assets/icon/icon.png
    - assets/icon/large-vup-logo-single.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

msix_config:
  display_name: Vup Cloud Storage
  publisher_display_name: redsolver
  identity_name: app.vup
  msix_version: 0.7.5.0
  logo_path: assets\icon\large-vup-logo-single.png
  capabilities: "internetClientServer,privateNetworkClientServer"
