name: vup
description: Vup Cloud Storage

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.14.1+1401

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  unicons: ^2.1.1
  hive: ^2.2.3
  flutter_spinkit: ^5.1.0
  clipboard: ^0.1.3
  ffmpeg_kit_flutter_full: ^5.1.0
  simple_observable: ^2.0.0
  flutter_svg: ^2.0.4
  path_provider: ^2.0.14
  beamer: ^1.5.3
  path: ^1.8.3
  convert: ^3.1.1
  mime: ^1.0.4
  multi_split_view: 1.12.0
  filesize:
    git: https://github.com/redsolver/filesize.git
  timeago: ^3.4.0
  xdg_directories: ^1.0.0
  file_selector: ^0.9.2+4
  file_selector_linux: ^0.9.1+2
  file_selector_macos: ^0.9.0+7
  file_selector_windows: ^0.9.1+7
  file_picker: ^5.2.6
  # path: /home/redsolver/tmp/flutter_file_picker
  permission_handler: ^10.2.0
  hive_flutter: ^1.1.0
  # simple_json_mapper: ^2.1.0
  # workmanager: ^0.4.1
  # android_intent_plus: ^1.0.2
  open_file:
    git:
      url: https://github.com/miDeb/open_file.git
      ref: no_system
  open_settings: ^2.0.1
  flutter_advanced_segment: ^3.0.0
  selectable_autolink_text: ^2.3.0
  url_launcher: ^6.1.10
  html: ^0.15.2
  filesystem_dac:
    # path: ../fs-dac/dac
    git:
      url: https://github.com/redsolver/skyfs.git
      path: dac
  state_notifier: ^0.7.2+1
  flutter_state_notifier: ^0.7.3
  universal_platform: ^1.0.0+1
  desktop_drop: ^0.1.2
  uuid: ^3.0.5
  flutter_blurhash: ^0.7.0
  pool: ^1.5.0
  intl: ^0.18.0
  shimmer: ^3.0.0
  just_audio: ^0.9.32
  # just_audio_libwinmedia: ^0.0.4
  audio_video_progress_bar: ^1.0.1
  qr_flutter: ^4.0.0
  flutter_local_notifications: ^14.1.1
  flutter_highlight: ^0.7.0
  # new_keyboard_shortcuts: ^0.1.4
  watcher: ^1.0.2
  alfred:
    git:
      url: https://github.com/redsolver/alfred.git
  share_plus: ^6.3.1
  package_info_plus: ^3.0.3
  string_validator: ^1.0.0
  # printing: ^5.6.3
  retry: ^3.1.0
  uni_links: ^0.5.1
  device_info_plus: ^8.1.0
  network_info_plus: ^3.0.2
  tray_manager: ^0.2.0
  bitsdojo_window: ^0.1.5
  flutter_background: ^1.2.0
  # TODO feedback: ^2.6.0
  flutter_colorpicker: ^1.0.3
  stash: 4.0.1
  stash_hive: 4.0.1
  tuple: ^2.0.0
  subtitle: ^0.1.0-beta.3
  xml: ^6.2.2
  mno_streamer: 0.1.1
  archive: ^3.3.7
  launch_at_startup: ^0.2.2
  hive_crdt: ^2.0.2
  random_string: ^2.3.1
  draggable_scrollbar: ^0.1.0
  xml2json: ^6.1.0
  dart_chromecast: ^0.3.3
  contextmenu: ^3.0.0
  flutter_secure_storage: ^8.0.0
  local_auth: ^2.1.6
  dart_discord_rpc:
    git: https://github.com/alexmercerind/dart_discord_rpc.git
  s5_server:
    # path: ../s5_server
    git: https://github.com/s5-dev/S5.git
  lib5: ^0.1.0
  ffi: ^2.0.1
  flutter_rust_bridge: ^1.73.0
  exif: ^3.0.0
  thumbhash_flutter: ^0.0.1
  yaml: ^3.1.1
  replicate: ^1.0.0
  cryptography: ^2.5.0

  # flutter_acrylic: ^0.1.0
  # explo_capture: ^0.1.0+2
  # receive_sharing_intent: ^1.4.5

dev_dependencies:
  #flutter_test:
  #  sdk: flutter
  # simple_json: ^2.1.1
  build_runner: ^2.4.4
  hive_generator: ^2.0.0
  json_serializable: ^6.7.0
  flutter_launcher_icons: ^0.13.1
  dart_code_metrics: ^5.7.4
  msix: ^3.13.3
  flutter_lints: ^2.0.1
  ffigen: ^8.0.2

dependency_overrides:
  # path: 1.8.1
  archive: 3.1.5
  ffi: 2.0.1
  xml: 6.3.0
  intl: 0.18.0
  xdg_directories: 1.0.0
  cli_util: 0.4.0
  image: 4.0.8
  http: 1.0.0
  # meta: 1.9.0
  # collection: 1.17.1
  source_span: ^1.10.0
  flutter_secure_storage_linux:
    git:
      url: https://github.com/Mino5531/flutter_secure_storage.git
      ref: develop
      path: flutter_secure_storage_linux

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  image_path_ios: "assets/icon/ios.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/adaptive_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/vscode-material-icon-theme/
    - assets/images/
    - assets/web/
    - assets/icon/tray_icon.png
    - assets/icon/tray_icon.ico
    - assets/icon/icon.png
    - assets/icon/large-vup-logo-single.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

msix_config:
  display_name: Vup Cloud Storage
  publisher_display_name: redsolver
  identity_name: app.vup
  msix_version: 0.7.5.0
  logo_path: assets\icon\large-vup-logo-single.png
  capabilities: "internetClientServer,privateNetworkClientServer"
